[workspace]
members = [
    "crates/network_scanner",
    "crates/http_fuzzer",
    "crates/cve_scanner",
    "crates/main_orchestrator",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Quentin GUILLAUME & Team"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0" # Pour une gestion d'erreurs simplifiée 